### ISSUE TITLE
Начать хоть что-то делать

### ISSUE THREAD

**Issue by MrKimkimora** [Four-el-Ltd/Trade-And-Fraction#29]
Делай
![GKetILfbkAA9weR](https://github.com/Four-el-Ltd/Trade-And-Fraction/assets/144221261/4a160f7e-3947-4585-b430-6d7c71379442)

**Comment by Ruslanllll** [comment]
Буду считать что это обращение к Вите

**Comment by MrKimkimora** [comment]
Я жду МаНуСкРиПтЫ

**Comment by Ruslanllll** [comment]
> Я жду МаНуСкРиПтЫ

Как только так сразу :trollface:
